### ISSUE TITLE
Error in DateTimeParser

### ISSUE THREAD

**Issue by danielcsant** [Stratio/Sparkta#1051]
NotSerializableException when using an inputFormat like "date" and the field is like "2015-Sep-22 10:37:39.16211"

**Comment by dvallejo** [comment]
Invalid format for a java.util.Date. Maybe it's possible to do it with Joda. Pending to test it.

**Comment by sgomezg** [comment]
Maybe related with #1038

**Comment by sgomezg** [comment]
StackTrace: 

```
org.apache.spark.SparkException: Task not serializable
	at org.apache.spark.util.ClosureCleaner$.ensureSerializable(ClosureCleaner.scala:315)
	at org.apache.spark.util.ClosureCleaner$.org$apache$spark$util$ClosureCleaner$$clean(ClosureCleaner.scala:305)
	at org.apache.spark.util.ClosureCleaner$.clean(ClosureCleaner.scala:132)
	at org.apache.spark.SparkContext.clean(SparkContext.scala:1893)
	at org.apache.spark.streaming.dstream.DStream$$anonfun$map$1.apply(DStream.scala:528)
	at org.apache.spark.streaming.dstream.DStream$$anonfun$map$1.apply(DStream.scala:528)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:147)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:108)
	at org.apache.spark.SparkContext.withScope(SparkContext.scala:681)
	at org.apache.spark.streaming.StreamingContext.withScope(StreamingContext.scala:258)
	at org.apache.spark.streaming.dstream.DStream.map(DStream.scala:527)
	at com.stratio.sparkta.driver.SparktaJob$.applyParsers(SparktaJob.scala:85)
	at com.stratio.sparkta.driver.SparktaJob$.runSparktaJob(SparktaJob.scala:77)
	at com.stratio.sparkta.driver.service.StreamingContextService.standAloneStreamingContext(StreamingContextService.scala:49)
	at com.stratio.sparkta.serving.api.actor.LocalSparkStreamingContextActor$$anonfun$1.apply$mcV$sp(LocalSparkStreamingContextActor.scala:55)
	at com.stratio.sparkta.serving.api.actor.LocalSparkStreamingContextActor$$anonfun$1.apply(LocalSparkStreamingContextActor.scala:53)
	at com.stratio.sparkta.serving.api.actor.LocalSparkStreamingContextActor$$anonfun$1.apply(LocalSparkStreamingContextActor.scala:53)
	at scala.util.Try$.apply(Try.scala:161)
	at com.stratio.sparkta.serving.api.actor.LocalSparkStreamingContextActor.com$stratio$sparkta$serving$api$actor$LocalSparkStreamingContextActor$$doInitSparktaContext(LocalSparkStreamingContextActor.scala:53)
	at com.stratio.sparkta.serving.api.actor.LocalSparkStreamingContextActor$$anonfun$receive$1.applyOrElse(LocalSparkStreamingContextActor.scala:44)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:465)
	at com.stratio.sparkta.serving.api.actor.InstrumentedActor.aroundReceive(InstrumentedActor.scala:21)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
	at akka.actor.ActorCell.invoke(ActorCell.scala:487)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
	at akka.dispatch.Mailbox.run(Mailbox.scala:220)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.io.NotSerializableException: org.joda.time.format.DateTimeFormatter
Serialization stack:
	- object not serializable (class: org.joda.time.format.DateTimeFormatter, value: org.joda.time.format.DateTimeFormatter@6c17d5fa)
	- field (class: scala.util.Left, name: a, type: class java.lang.Object)
	- object (class scala.util.Left, Left(org.joda.time.format.DateTimeFormatter@6c17d5fa))
	- field (class: scala.Some, name: x, type: class java.lang.Object)
	- object (class scala.Some, Some(Left(org.joda.time.format.DateTimeFormatter@6c17d5fa)))
	- field (class: com.stratio.sparkta.plugin.parser.datetime.DateTimeParser, name: com$stratio$sparkta$plugin$parser$datetime$DateTimeParser$$formatter, type: class scala.Option)
	- object (class com.stratio.sparkta.plugin.parser.datetime.DateTimeParser, Parameterizable(Map(inputFormat -> dateTime)))
	- field (class: com.stratio.sparkta.driver.SparktaJob$$anonfun$applyParsers$1, name: x3$1, type: class com.stratio.sparkta.sdk.Parser)
	- object (class com.stratio.sparkta.driver.SparktaJob$$anonfun$applyParsers$1, <function1>)
	at org.apache.spark.serializer.SerializationDebugger$.improveException(SerializationDebugger.scala:40)
	at org.apache.spark.serializer.JavaSerializationStream.writeObject(JavaSerializer.scala:47)
	at org.apache.spark.serializer.JavaSerializerInstance.serialize(JavaSerializer.scala:81)
	at org.apache.spark.util.ClosureCleaner$.ensureSerializable(ClosureCleaner.scala:312)
	... 30 more
```

**Comment by danielcsant** [comment]
Issue migrated to JIRA.
