### ISSUE TITLE
Unable to build release 0.5.0_spark-1.3

### ISSUE THREAD

**Issue by elenapascual** [Stratio/sparkta#403]
Hello!
I downloaded 0.5.0_spark-1.3.tar.gz, when packaging it as it is said: mvn clean package -Ppackage and the three dependencies installed the following error came up: 

*Failed to execute goal com.stratio.mojo.unix:unix-maven-plugin:1.1.2:package-deb (engine) on project dist: Unable to create package. Command 'fakeroot' returned a non-null exit code: 2*

I tried as root and non-root.
On a CentOS 6.6 and on a Linux Mint 17.1. 

What could that be?
Thanks!

**Comment by danielcsant** [comment]
Hi

Did you install the programs needed to package? It use to be the problem when packaging

https://github.com/Stratio/sparkta#build

**Comment by elenapascual** [comment]
Yes, I did. The three programs had been previously installed.

**Comment by danielcsant** [comment]
Ok, we'll check it ASAP

**Comment by sgomezg** [comment]
The v0.5.0 is packaging well but the v0.5.0_spark-1.3 doesn't

**Comment by sgomezg** [comment]
```
[ERROR] Failed to execute goal com.stratio.mojo.unix:unix-maven-plugin:1.1.2:package-deb (engine) on project dist: Unable to create package. Command 'fakeroot' returned a non-null exit code: 2 -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.stratio.mojo.unix:unix-maven-plugin:1.1.2:package-deb (engine) on project dist: Unable to create package.
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:216)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Unable to create package.
	at com.stratio.mojo.unix.maven.MojoHelper$Execution.execute(MojoHelper.java:310)
	at com.stratio.mojo.unix.maven.plugin.AbstractPackageMojo.execute(AbstractPackageMojo.java:68)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 20 more
Caused by: java.io.IOException: Command 'fakeroot' returned a non-null exit code: 2
	at com.stratio.mojo.unix.util.SystemCommand$ExecutionResult.assertSuccess(SystemCommand.java:135)
	at com.stratio.mojo.unix.deb.DpkgDeb.execute(DpkgDeb.java:94)
	at com.stratio.mojo.unix.maven.deb.DebUnixPackage$DebPreparedPackage.packageToFile(DebUnixPackage.java:197)
	at com.stratio.mojo.unix.maven.MojoHelper$Execution.execute(MojoHelper.java:294)
	... 23 more
[ERROR]
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

**Comment by sgomezg** [comment]
Solved. Please use [v0.5.0-spark-1.3](https://github.com/Stratio/sparkta/releases/tag/0.5.0-spark-1.3)
Let me know if the problems persist.
