### ISSUE TITLE
kafka Input messages larger than 4k cause an error in the jasonparser

### ISSUE THREAD

**Issue by elenapascual** [Stratio/sparkta#431]
Hello!

On the following version of sparkta "versions/sparkta-with-spark-1.3" and using kafka as input, the events passed than are larger than 4k (approx), are split at position 4096(approx). The json event then becomes malformed and the jsonparser complains. The kafka producer that it has been used in this case is a flume agent. It seems that one of three kafka actors: Broker, producer or consumer adds a line feed (LF) when it reaches that position.
I have tried changing several parameters on the broker configuration without success.  I have also tried adding consumer parameters in the policy with unsuccessful results too.

Here is the error:

*ERROR JobScheduler - Error running job streaming job 1437129860000 ms.0
org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 182.0 failed 1 times, most recent failure: Lost task 0.0 in stage 182.0 (TID 99, localhost): org.kitesdk.morphline.api.MorphlineRuntimeException: com.fasterxml.jackson.core.JsonParseException: Unexpected end-of-input in VALUE_STRING
 at [Source: java.io.ByteArrayInputStream@481195d2; line: 1, column: 4203]
	at org.kitesdk.morphline.stdio.AbstractParser.doProcess(AbstractParser.java:98)
	at org.kitesdk.morphline.base.AbstractCommand.process(AbstractCommand.java:156)
	at org.kitesdk.morphline.base.AbstractCommand.doProcess(AbstractCommand.java:181)
	at org.kitesdk.morphline.base.AbstractCommand.process(AbstractCommand.java:156)
	at com.stratio.sparkta.plugin.parser.morphline.MorphlineImpl.process(MorphlinesParser.scala:76)
	at com.stratio.sparkta.plugin.parser.morphline.MorphlinesParser.parse(MorphlinesParser.scala:53)
	at com.stratio.sparkta.driver.service.SparktaJob$$anonfun$applyParsers$1.apply(StreamingContextService.scala:93)
	at com.stratio.sparkta.driver.service.SparktaJob$$anonfun$applyParsers$1.apply(StreamingContextService.scala:93)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:328)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:328)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:328)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:328)
	at org.apache.spark.storage.MemoryStore.unrollSafely(MemoryStore.scala:249)
	at org.apache.spark.CacheManager.putInBlockManager(CacheManager.scala:172)
	at org.apache.spark.CacheManager.getOrCompute(CacheManager.scala:79)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:242)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:68)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:41)
	at org.apache.spark.scheduler.Task.run(Task.scala:64)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:203)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.fasterxml.jackson.core.JsonParseException: Unexpected end-of-input in VALUE_STRING
 at [Source: java.io.ByteArrayInputStream@481195d2; line: 1, column: 4203]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1524)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:557)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportInvalidEOF(ParserMinimalBase.java:487)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportInvalidEOF(ParserMinimalBase.java:481)
	at com.fasterxml.jackson.core.base.ParserBase.loadMoreGuaranteed(ParserBase.java:440)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._finishString2(UTF8StreamJsonParser.java:2169)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._finishString(UTF8StreamJsonParser.java:2150)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.getText(UTF8StreamJsonParser.java:282)
	at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeArray(JsonNodeDeserializer.java:262)
	at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:225)
	at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:63)
	at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:14)
	at com.fasterxml.jackson.databind.MappingIterator.nextValue(MappingIterator.java:189)
	at org.kitesdk.morphline.json.ReadJsonBuilder$ReadJson.doProcess(ReadJsonBuilder.java:110)
	at org.kitesdk.morphline.stdio.AbstractParser.doProcess(AbstractParser.java:96)
	... 22 more

Driver stacktrace:
	at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1203)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1192)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1191)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1191)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:693)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:693)
	at scala.Option.foreach(Option.scala:236)
	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:693)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1393)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1354)
	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:48)*

**Comment by dmorales-stratio** [comment]
Please, try to isolate the error to really know where is the issue. For
example:

Using a kafka-console-consumer, are the messages ok? If so, then it could
be a problem in sparkta, in other case, check your flume-kafka integration.




2015-07-17 12:46 GMT+02:00 Elena <notifications@github.com>:

> Hello!
>
> On the following version of sparkta "versions/sparkta-with-spark-1.3" and
> using kafka as input, the events passed than are larger than 4k (approx),
> are split at position 4096(approx). The json event then becomes malformed
> and the jsonparser complains. The kafka producer that it has been used in
> this case is a flume agent. It seems that one of three kafka actors:
> Broker, producer or consumer adds a line feed (LF) when it reaches that
> position.
> I have tried changing several parameters on the broker configuration
> without success. I have also tried adding consumer parameters in the policy
> with unsuccessful results too.
>
> Here is the error:
>
> *ERROR JobScheduler - Error running job streaming job 1437129860000 ms.0
> org.apache.spark.SparkException: Job aborted due to stage failure: Task 0
> in stage 182.0 failed 1 times, most recent failure: Lost task 0.0 in stage
> 182.0 (TID 99, localhost):
> org.kitesdk.morphline.api.MorphlineRuntimeException:
> com.fasterxml.jackson.core.JsonParseException: Unexpected end-of-input in
> VALUE_STRING
> at [Source: java.io.ByteArrayInputStream@481195d
> <https://github.com/java.io.ByteArrayInputStream/sparkta/commit/481195d2>;
> line: 1, column: 4203]
> at
> org.kitesdk.morphline.stdio.AbstractParser.doProcess(AbstractParser.java:98)
> at
> org.kitesdk.morphline.base.AbstractCommand.process(AbstractCommand.java:156)
> at
> org.kitesdk.morphline.base.AbstractCommand.doProcess(AbstractCommand.java:181)
> at
> org.kitesdk.morphline.base.AbstractCommand.process(AbstractCommand.java:156)
> at
> com.stratio.sparkta.plugin.parser.morphline.MorphlineImpl.process(MorphlinesParser.scala:76)
> at
> com.stratio.sparkta.plugin.parser.morphline.MorphlinesParser.parse(MorphlinesParser.scala:53)
> at
> com.stratio.sparkta.driver.service.SparktaJob$$anonfun$applyParsers$1.apply(StreamingContextService.scala:93)
> at
> com.stratio.sparkta.driver.service.SparktaJob$$anonfun$applyParsers$1.apply(StreamingContextService.scala:93)
> at scala.collection.Iterator$$anon$11.next(Iterator.scala:328)
> at scala.collection.Iterator$$anon$11.next(Iterator.scala:328)
> at scala.collection.Iterator$$anon$11.next(Iterator.scala:328)
> at scala.collection.Iterator$$anon$11.next(Iterator.scala:328)
> at org.apache.spark.storage.MemoryStore.unrollSafely(MemoryStore.scala:249)
> at org.apache.spark.CacheManager.putInBlockManager(CacheManager.scala:172)
> at org.apache.spark.CacheManager.getOrCompute(CacheManager.scala:79)
> at org.apache.spark.rdd.RDD.iterator(RDD.scala:242)
> at
> org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:68)
> at
> org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:41)
> at org.apache.spark.scheduler.Task.run(Task.scala:64)
> at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:203)
> at
> java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
> at
> java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
> at java.lang.Thread.run(Thread.java:745)
> Caused by: com.fasterxml.jackson.core.JsonParseException: Unexpected
> end-of-input in VALUE_STRING
> at [Source: java.io.ByteArrayInputStream@481195d
> <https://github.com/java.io.ByteArrayInputStream/sparkta/commit/481195d2>;
> line: 1, column: 4203]
> at
> com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1524)
> at
> com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:557)
> at
> com.fasterxml.jackson.core.base.ParserMinimalBase._reportInvalidEOF(ParserMinimalBase.java:487)
> at
> com.fasterxml.jackson.core.base.ParserMinimalBase._reportInvalidEOF(ParserMinimalBase.java:481)
> at
> com.fasterxml.jackson.core.base.ParserBase.loadMoreGuaranteed(ParserBase.java:440)
> at
> com.fasterxml.jackson.core.json.UTF8StreamJsonParser._finishString2(UTF8StreamJsonParser.java:2169)
> at
> com.fasterxml.jackson.core.json.UTF8StreamJsonParser._finishString(UTF8StreamJsonParser.java:2150)
> at
> com.fasterxml.jackson.core.json.UTF8StreamJsonParser.getText(UTF8StreamJsonParser.java:282)
> at
> com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeArray(JsonNodeDeserializer.java:262)
> at
> com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:225)
> at
> com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:63)
> at
> com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:14)
> at
> com.fasterxml.jackson.databind.MappingIterator.nextValue(MappingIterator.java:189)
> at
> org.kitesdk.morphline.json.ReadJsonBuilder$ReadJson.doProcess(ReadJsonBuilder.java:110)
> at
> org.kitesdk.morphline.stdio.AbstractParser.doProcess(AbstractParser.java:96)
> ... 22 more
>
> Driver stacktrace:
> at org.apache.spark.scheduler.DAGScheduler.org
> $apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1203)
> at
> org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1192)
> at
> org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1191)
> at
> scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
> at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
> at
> org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1191)
> at
> org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:693)
> at
> org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:693)
> at scala.Option.foreach(Option.scala:236)
> at
> org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:693)
> at
> org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1393)
> at
> org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1354)
> at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:48)*
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Stratio/sparkta/issues/431>.
>



-- 

David Morales de Frías  ::  +34 607 010 411 :: @dmoralesdf
<https://twitter.com/dmoralesdf>


<http://www.stratio.com/>
Vía de las dos Castillas, 33, Ática 4, 3ª Planta
28224 Pozuelo de Alarcón, Madrid
Tel: +34 91 828 6473 // www.stratio.com // *@stratiobd
<https://twitter.com/StratioBD>*

**Comment by elenapascual** [comment]
After a careful review it turns out that I made a mistake in the flume agent. The length of the deserializer line (agent.sources.deserializer.maxLineLength) was set to 4096 and that is why the messages were cut before being sent.

After setting this parameter with a bigger number, sparkta received the entire message and processed it  all right. 

Thanks and sorry for the fuss ;)

**Comment by dmorales-stratio** [comment]
Don't worry, when several technologies are involved in an issue it's a nice
idea to find out where is the problem.

Regards

2015-07-17 13:45 GMT+02:00 Elena <notifications@github.com>:

> After a careful review it turns out that I made a mistake in the flume
> agent. The length of the deserializer line
> (agent.sources.deserializer.maxLineLength) was set to 4096 and that is why
> the messages were cut before being sent.
>
> After setting this parameter with a bigger number, sparkta received the
> entire message and processed it all right.
>
> Thanks and sorry for the fuss ;)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Stratio/sparkta/issues/431#issuecomment-122253408>.
>



-- 

David Morales de Frías  ::  +34 607 010 411 :: @dmoralesdf
<https://twitter.com/dmoralesdf>


<http://www.stratio.com/>
Vía de las dos Castillas, 33, Ática 4, 3ª Planta
28224 Pozuelo de Alarcón, Madrid
Tel: +34 91 828 6473 // www.stratio.com // *@stratiobd
<https://twitter.com/StratioBD>*
